name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v5
    - name: Build the Docker image
    # Docker builds an image using the code here, specifically using the file named Dockerfile and tag it with what follows after
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/liatrio-exercise:${{ github.sha }} --tag ${{ secrets.DOCKER_HUB_USERNAME }}/liatrio-exercise:latest

    - name: Start Container To See Code Results
    # Docker runs (-d detached so GitHub Actions can run this in the background) -p for port, maps port 80 to port 3000 and adds name
      run: docker run -d -p 80:3000 --name liatrio-webapp ${{ secrets.DOCKER_HUB_USERNAME }}/liatrio-exercise:${{ github.sha }}
    
    - name: Run Liatrio Tests
    # Runs tests provided by Liatrio (using SHA version because latest version has unfinished test that defaults error)
      uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Image
    # Push image that has own version ID for every successful run (Docker images on computer can be public so other people can see/access/download, like repo for images)
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/liatrio-exercise:${{ github.sha }} && docker push ${{ secrets.DOCKER_HUB_USERNAME }}/liatrio-exercise:latest

    # Pushing to Google Cloud Run
    - name: Access to Google Cloud Run
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/343446715177/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
        service_account: '343446715177-compute@developer.gserviceaccount.com'
    
    - name: Deploy to Google Cloud Run
      id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'liatrio-webapp'
        region: 'us-central1'
        image: 'docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/liatrio-exercise:${{ github.sha }}'
        flags: '--allow-unauthenticated --port=3000'
     